// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protocol/proto/runner.proto

package runnerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Engine int32

const (
	Engine_ENGINE_UNSPECIFIED Engine = 0
	Engine_ENGINE_HOST        Engine = 1
	Engine_ENGINE_DOCKER      Engine = 2
)

// Enum value maps for Engine.
var (
	Engine_name = map[int32]string{
		0: "ENGINE_UNSPECIFIED",
		1: "ENGINE_HOST",
		2: "ENGINE_DOCKER",
	}
	Engine_value = map[string]int32{
		"ENGINE_UNSPECIFIED": 0,
		"ENGINE_HOST":        1,
		"ENGINE_DOCKER":      2,
	}
)

func (x Engine) Enum() *Engine {
	p := new(Engine)
	*p = x
	return p
}

func (x Engine) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Engine) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_runner_proto_enumTypes[0].Descriptor()
}

func (Engine) Type() protoreflect.EnumType {
	return &file_protocol_proto_runner_proto_enumTypes[0]
}

func (x Engine) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Engine.Descriptor instead.
func (Engine) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{0}
}

type TaskEventType int32

const (
	TaskEventType_TASK_EVENT_TYPE_UNSPECIFIED TaskEventType = 0
	TaskEventType_TASK_EVENT_TYPE_STARTED     TaskEventType = 1
	TaskEventType_TASK_EVENT_TYPE_STDOUT      TaskEventType = 2
	TaskEventType_TASK_EVENT_TYPE_STDERR      TaskEventType = 3
	TaskEventType_TASK_EVENT_TYPE_PROGRESS    TaskEventType = 4
	TaskEventType_TASK_EVENT_TYPE_RESULT      TaskEventType = 5
	TaskEventType_TASK_EVENT_TYPE_ERROR       TaskEventType = 6
	TaskEventType_TASK_EVENT_TYPE_COMPLETED   TaskEventType = 7
	TaskEventType_TASK_EVENT_TYPE_HEARTBEAT   TaskEventType = 8
)

// Enum value maps for TaskEventType.
var (
	TaskEventType_name = map[int32]string{
		0: "TASK_EVENT_TYPE_UNSPECIFIED",
		1: "TASK_EVENT_TYPE_STARTED",
		2: "TASK_EVENT_TYPE_STDOUT",
		3: "TASK_EVENT_TYPE_STDERR",
		4: "TASK_EVENT_TYPE_PROGRESS",
		5: "TASK_EVENT_TYPE_RESULT",
		6: "TASK_EVENT_TYPE_ERROR",
		7: "TASK_EVENT_TYPE_COMPLETED",
		8: "TASK_EVENT_TYPE_HEARTBEAT",
	}
	TaskEventType_value = map[string]int32{
		"TASK_EVENT_TYPE_UNSPECIFIED": 0,
		"TASK_EVENT_TYPE_STARTED":     1,
		"TASK_EVENT_TYPE_STDOUT":      2,
		"TASK_EVENT_TYPE_STDERR":      3,
		"TASK_EVENT_TYPE_PROGRESS":    4,
		"TASK_EVENT_TYPE_RESULT":      5,
		"TASK_EVENT_TYPE_ERROR":       6,
		"TASK_EVENT_TYPE_COMPLETED":   7,
		"TASK_EVENT_TYPE_HEARTBEAT":   8,
	}
)

func (x TaskEventType) Enum() *TaskEventType {
	p := new(TaskEventType)
	*p = x
	return p
}

func (x TaskEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_runner_proto_enumTypes[1].Descriptor()
}

func (TaskEventType) Type() protoreflect.EnumType {
	return &file_protocol_proto_runner_proto_enumTypes[1]
}

func (x TaskEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskEventType.Descriptor instead.
func (TaskEventType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{1}
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,7,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,8,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Stream        bool                   `protobuf:"varint,9,opt,name=stream,proto3" json:"stream,omitempty"`
	AuthToken     string                 `protobuf:"bytes,10,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	InputJson     []byte                 `protobuf:"bytes,11,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	Engine        Engine                 `protobuf:"varint,12,opt,name=engine,proto3,enum=agentflow.runner.v1.Engine" json:"engine,omitempty"`
	SandboxPolicy *SandboxPolicy         `protobuf:"bytes,13,opt,name=sandbox_policy,json=sandboxPolicy,proto3" json:"sandbox_policy,omitempty"`
	Docker        *DockerSpec            `protobuf:"bytes,14,opt,name=docker,proto3" json:"docker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_protocol_proto_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TaskRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *TaskRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TaskRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TaskRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *TaskRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *TaskRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *TaskRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *TaskRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *TaskRequest) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

func (x *TaskRequest) GetEngine() Engine {
	if x != nil {
		return x.Engine
	}
	return Engine_ENGINE_UNSPECIFIED
}

func (x *TaskRequest) GetSandboxPolicy() *SandboxPolicy {
	if x != nil {
		return x.SandboxPolicy
	}
	return nil
}

func (x *TaskRequest) GetDocker() *DockerSpec {
	if x != nil {
		return x.Docker
	}
	return nil
}

type SandboxPolicy struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Enabled                 bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ReadOnly                bool                   `protobuf:"varint,2,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	AllowNetwork            bool                   `protobuf:"varint,3,opt,name=allow_network,json=allowNetwork,proto3" json:"allow_network,omitempty"`
	AllowedWorkingDirs      []string               `protobuf:"bytes,4,rep,name=allowed_working_dirs,json=allowedWorkingDirs,proto3" json:"allowed_working_dirs,omitempty"`
	AllowedReadPaths        []string               `protobuf:"bytes,5,rep,name=allowed_read_paths,json=allowedReadPaths,proto3" json:"allowed_read_paths,omitempty"`
	AllowedWritePaths       []string               `protobuf:"bytes,6,rep,name=allowed_write_paths,json=allowedWritePaths,proto3" json:"allowed_write_paths,omitempty"`
	BlockedCommandFragments []string               `protobuf:"bytes,7,rep,name=blocked_command_fragments,json=blockedCommandFragments,proto3" json:"blocked_command_fragments,omitempty"`
	AllowedEnvKeys          []string               `protobuf:"bytes,8,rep,name=allowed_env_keys,json=allowedEnvKeys,proto3" json:"allowed_env_keys,omitempty"`
	DeniedEnvKeys           []string               `protobuf:"bytes,9,rep,name=denied_env_keys,json=deniedEnvKeys,proto3" json:"denied_env_keys,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SandboxPolicy) Reset() {
	*x = SandboxPolicy{}
	mi := &file_protocol_proto_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPolicy) ProtoMessage() {}

func (x *SandboxPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPolicy.ProtoReflect.Descriptor instead.
func (*SandboxPolicy) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SandboxPolicy) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *SandboxPolicy) GetAllowNetwork() bool {
	if x != nil {
		return x.AllowNetwork
	}
	return false
}

func (x *SandboxPolicy) GetAllowedWorkingDirs() []string {
	if x != nil {
		return x.AllowedWorkingDirs
	}
	return nil
}

func (x *SandboxPolicy) GetAllowedReadPaths() []string {
	if x != nil {
		return x.AllowedReadPaths
	}
	return nil
}

func (x *SandboxPolicy) GetAllowedWritePaths() []string {
	if x != nil {
		return x.AllowedWritePaths
	}
	return nil
}

func (x *SandboxPolicy) GetBlockedCommandFragments() []string {
	if x != nil {
		return x.BlockedCommandFragments
	}
	return nil
}

func (x *SandboxPolicy) GetAllowedEnvKeys() []string {
	if x != nil {
		return x.AllowedEnvKeys
	}
	return nil
}

func (x *SandboxPolicy) GetDeniedEnvKeys() []string {
	if x != nil {
		return x.DeniedEnvKeys
	}
	return nil
}

type DockerMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerMount) Reset() {
	*x = DockerMount{}
	mi := &file_protocol_proto_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerMount) ProtoMessage() {}

func (x *DockerMount) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerMount.ProtoReflect.Descriptor instead.
func (*DockerMount) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{2}
}

func (x *DockerMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DockerMount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DockerMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type DockerSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Image           string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	WorkDir         string                 `protobuf:"bytes,2,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	User            string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	NetworkDisabled bool                   `protobuf:"varint,4,opt,name=network_disabled,json=networkDisabled,proto3" json:"network_disabled,omitempty"`
	ReadOnlyRootFs  bool                   `protobuf:"varint,5,opt,name=read_only_root_fs,json=readOnlyRootFs,proto3" json:"read_only_root_fs,omitempty"`
	Mounts          []*DockerMount         `protobuf:"bytes,6,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DockerSpec) Reset() {
	*x = DockerSpec{}
	mi := &file_protocol_proto_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerSpec) ProtoMessage() {}

func (x *DockerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerSpec.ProtoReflect.Descriptor instead.
func (*DockerSpec) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{3}
}

func (x *DockerSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DockerSpec) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *DockerSpec) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DockerSpec) GetNetworkDisabled() bool {
	if x != nil {
		return x.NetworkDisabled
	}
	return false
}

func (x *DockerSpec) GetReadOnlyRootFs() bool {
	if x != nil {
		return x.ReadOnlyRootFs
	}
	return false
}

func (x *DockerSpec) GetMounts() []*DockerMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_protocol_proto_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{4}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_protocol_proto_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_protocol_proto_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UnixTime      int64                  `protobuf:"varint,3,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_protocol_proto_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUnixTime() int64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

type StartedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartedPayload) Reset() {
	*x = StartedPayload{}
	mi := &file_protocol_proto_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartedPayload) ProtoMessage() {}

func (x *StartedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartedPayload.ProtoReflect.Descriptor instead.
func (*StartedPayload) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{8}
}

func (x *StartedPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPayload) Reset() {
	*x = StreamPayload{}
	mi := &file_protocol_proto_runner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPayload) ProtoMessage() {}

func (x *StreamPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPayload.ProtoReflect.Descriptor instead.
func (*StreamPayload) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{9}
}

func (x *StreamPayload) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

type ProgressPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Percent       uint32                 `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressPayload) Reset() {
	*x = ProgressPayload{}
	mi := &file_protocol_proto_runner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressPayload) ProtoMessage() {}

func (x *ProgressPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressPayload.ProtoReflect.Descriptor instead.
func (*ProgressPayload) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{10}
}

func (x *ProgressPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressPayload) GetPercent() uint32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type ResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	OutputJson    []byte                 `protobuf:"bytes,2,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultPayload) Reset() {
	*x = ResultPayload{}
	mi := &file_protocol_proto_runner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultPayload) ProtoMessage() {}

func (x *ResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultPayload.ProtoReflect.Descriptor instead.
func (*ResultPayload) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{11}
}

func (x *ResultPayload) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ResultPayload) GetOutputJson() []byte {
	if x != nil {
		return x.OutputJson
	}
	return nil
}

type ErrorPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,2,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorPayload) Reset() {
	*x = ErrorPayload{}
	mi := &file_protocol_proto_runner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorPayload) ProtoMessage() {}

func (x *ErrorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorPayload.ProtoReflect.Descriptor instead.
func (*ErrorPayload) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorPayload) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type CompletedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	DurationMs    uint64                 `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletedPayload) Reset() {
	*x = CompletedPayload{}
	mi := &file_protocol_proto_runner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedPayload) ProtoMessage() {}

func (x *CompletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedPayload.ProtoReflect.Descriptor instead.
func (*CompletedPayload) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{13}
}

func (x *CompletedPayload) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CompletedPayload) GetDurationMs() uint64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type HeartbeatPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPayload) Reset() {
	*x = HeartbeatPayload{}
	mi := &file_protocol_proto_runner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPayload) ProtoMessage() {}

func (x *HeartbeatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPayload.ProtoReflect.Descriptor instead.
func (*HeartbeatPayload) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{14}
}

func (x *HeartbeatPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TaskId    string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StepId    string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Type      TaskEventType          `protobuf:"varint,4,opt,name=type,proto3,enum=agentflow.runner.v1.TaskEventType" json:"type,omitempty"`
	Timestamp string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RunnerId  string                 `protobuf:"bytes,6,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TaskEvent_Started
	//	*TaskEvent_Stdout
	//	*TaskEvent_Stderr
	//	*TaskEvent_Progress
	//	*TaskEvent_Result
	//	*TaskEvent_Error
	//	*TaskEvent_Completed
	//	*TaskEvent_Heartbeat
	Payload       isTaskEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_protocol_proto_runner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{15}
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TaskEvent) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *TaskEvent) GetType() TaskEventType {
	if x != nil {
		return x.Type
	}
	return TaskEventType_TASK_EVENT_TYPE_UNSPECIFIED
}

func (x *TaskEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TaskEvent) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *TaskEvent) GetPayload() isTaskEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskEvent) GetStarted() *StartedPayload {
	if x != nil {
		if x, ok := x.Payload.(*TaskEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *TaskEvent) GetStdout() *StreamPayload {
	if x != nil {
		if x, ok := x.Payload.(*TaskEvent_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *TaskEvent) GetStderr() *StreamPayload {
	if x != nil {
		if x, ok := x.Payload.(*TaskEvent_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *TaskEvent) GetProgress() *ProgressPayload {
	if x != nil {
		if x, ok := x.Payload.(*TaskEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *TaskEvent) GetResult() *ResultPayload {
	if x != nil {
		if x, ok := x.Payload.(*TaskEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *TaskEvent) GetError() *ErrorPayload {
	if x != nil {
		if x, ok := x.Payload.(*TaskEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *TaskEvent) GetCompleted() *CompletedPayload {
	if x != nil {
		if x, ok := x.Payload.(*TaskEvent_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *TaskEvent) GetHeartbeat() *HeartbeatPayload {
	if x != nil {
		if x, ok := x.Payload.(*TaskEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isTaskEvent_Payload interface {
	isTaskEvent_Payload()
}

type TaskEvent_Started struct {
	Started *StartedPayload `protobuf:"bytes,20,opt,name=started,proto3,oneof"`
}

type TaskEvent_Stdout struct {
	Stdout *StreamPayload `protobuf:"bytes,21,opt,name=stdout,proto3,oneof"`
}

type TaskEvent_Stderr struct {
	Stderr *StreamPayload `protobuf:"bytes,22,opt,name=stderr,proto3,oneof"`
}

type TaskEvent_Progress struct {
	Progress *ProgressPayload `protobuf:"bytes,23,opt,name=progress,proto3,oneof"`
}

type TaskEvent_Result struct {
	Result *ResultPayload `protobuf:"bytes,24,opt,name=result,proto3,oneof"`
}

type TaskEvent_Error struct {
	Error *ErrorPayload `protobuf:"bytes,25,opt,name=error,proto3,oneof"`
}

type TaskEvent_Completed struct {
	Completed *CompletedPayload `protobuf:"bytes,26,opt,name=completed,proto3,oneof"`
}

type TaskEvent_Heartbeat struct {
	Heartbeat *HeartbeatPayload `protobuf:"bytes,27,opt,name=heartbeat,proto3,oneof"`
}

func (*TaskEvent_Started) isTaskEvent_Payload() {}

func (*TaskEvent_Stdout) isTaskEvent_Payload() {}

func (*TaskEvent_Stderr) isTaskEvent_Payload() {}

func (*TaskEvent_Progress) isTaskEvent_Payload() {}

func (*TaskEvent_Result) isTaskEvent_Payload() {}

func (*TaskEvent_Error) isTaskEvent_Payload() {}

func (*TaskEvent_Completed) isTaskEvent_Payload() {}

func (*TaskEvent_Heartbeat) isTaskEvent_Payload() {}

type ConnectRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerToken   string                 `protobuf:"bytes,1,opt,name=runner_token,json=runnerToken,proto3" json:"runner_token,omitempty"`
	RunnerId      string                 `protobuf:"bytes,2,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	HostName      string                 `protobuf:"bytes,7,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	HostIp        string                 `protobuf:"bytes,8,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRegister) Reset() {
	*x = ConnectRegister{}
	mi := &file_protocol_proto_runner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRegister) ProtoMessage() {}

func (x *ConnectRegister) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRegister.ProtoReflect.Descriptor instead.
func (*ConnectRegister) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{16}
}

func (x *ConnectRegister) GetRunnerToken() string {
	if x != nil {
		return x.RunnerToken
	}
	return ""
}

func (x *ConnectRegister) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *ConnectRegister) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ConnectRegister) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConnectRegister) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConnectRegister) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ConnectRegister) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *ConnectRegister) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

type ConnectRegisterAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunnerId            string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	HeartbeatIntervalMs int64                  `protobuf:"varint,3,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	ServerTime          string                 `protobuf:"bytes,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConnectRegisterAck) Reset() {
	*x = ConnectRegisterAck{}
	mi := &file_protocol_proto_runner_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRegisterAck) ProtoMessage() {}

func (x *ConnectRegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRegisterAck.ProtoReflect.Descriptor instead.
func (*ConnectRegisterAck) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{17}
}

func (x *ConnectRegisterAck) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *ConnectRegisterAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConnectRegisterAck) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *ConnectRegisterAck) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

type ConnectHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerId      string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	RunnerToken   string                 `protobuf:"bytes,2,opt,name=runner_token,json=runnerToken,proto3" json:"runner_token,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectHeartbeat) Reset() {
	*x = ConnectHeartbeat{}
	mi := &file_protocol_proto_runner_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectHeartbeat) ProtoMessage() {}

func (x *ConnectHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectHeartbeat.ProtoReflect.Descriptor instead.
func (*ConnectHeartbeat) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{18}
}

func (x *ConnectHeartbeat) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *ConnectHeartbeat) GetRunnerToken() string {
	if x != nil {
		return x.RunnerToken
	}
	return ""
}

func (x *ConnectHeartbeat) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ServerPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    string                 `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPing) Reset() {
	*x = ServerPing{}
	mi := &file_protocol_proto_runner_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPing) ProtoMessage() {}

func (x *ServerPing) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPing.ProtoReflect.Descriptor instead.
func (*ServerPing) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{19}
}

func (x *ServerPing) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

type RunnerEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RunnerEnvelope_Register
	//	*RunnerEnvelope_Heartbeat
	//	*RunnerEnvelope_TaskEvent
	Payload       isRunnerEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerEnvelope) Reset() {
	*x = RunnerEnvelope{}
	mi := &file_protocol_proto_runner_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerEnvelope) ProtoMessage() {}

func (x *RunnerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerEnvelope.ProtoReflect.Descriptor instead.
func (*RunnerEnvelope) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{20}
}

func (x *RunnerEnvelope) GetPayload() isRunnerEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RunnerEnvelope) GetRegister() *ConnectRegister {
	if x != nil {
		if x, ok := x.Payload.(*RunnerEnvelope_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *RunnerEnvelope) GetHeartbeat() *ConnectHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*RunnerEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *RunnerEnvelope) GetTaskEvent() *TaskEvent {
	if x != nil {
		if x, ok := x.Payload.(*RunnerEnvelope_TaskEvent); ok {
			return x.TaskEvent
		}
	}
	return nil
}

type isRunnerEnvelope_Payload interface {
	isRunnerEnvelope_Payload()
}

type RunnerEnvelope_Register struct {
	Register *ConnectRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type RunnerEnvelope_Heartbeat struct {
	Heartbeat *ConnectHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type RunnerEnvelope_TaskEvent struct {
	TaskEvent *TaskEvent `protobuf:"bytes,3,opt,name=task_event,json=taskEvent,proto3,oneof"`
}

func (*RunnerEnvelope_Register) isRunnerEnvelope_Payload() {}

func (*RunnerEnvelope_Heartbeat) isRunnerEnvelope_Payload() {}

func (*RunnerEnvelope_TaskEvent) isRunnerEnvelope_Payload() {}

type ServerEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerEnvelope_RegisterAck
	//	*ServerEnvelope_RunTask
	//	*ServerEnvelope_CancelTask
	//	*ServerEnvelope_Ping
	Payload       isServerEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEnvelope) Reset() {
	*x = ServerEnvelope{}
	mi := &file_protocol_proto_runner_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEnvelope) ProtoMessage() {}

func (x *ServerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_runner_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEnvelope.ProtoReflect.Descriptor instead.
func (*ServerEnvelope) Descriptor() ([]byte, []int) {
	return file_protocol_proto_runner_proto_rawDescGZIP(), []int{21}
}

func (x *ServerEnvelope) GetPayload() isServerEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerEnvelope) GetRegisterAck() *ConnectRegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerEnvelope) GetRunTask() *TaskRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_RunTask); ok {
			return x.RunTask
		}
	}
	return nil
}

func (x *ServerEnvelope) GetCancelTask() *CancelTaskRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_CancelTask); ok {
			return x.CancelTask
		}
	}
	return nil
}

func (x *ServerEnvelope) GetPing() *ServerPing {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isServerEnvelope_Payload interface {
	isServerEnvelope_Payload()
}

type ServerEnvelope_RegisterAck struct {
	RegisterAck *ConnectRegisterAck `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerEnvelope_RunTask struct {
	RunTask *TaskRequest `protobuf:"bytes,2,opt,name=run_task,json=runTask,proto3,oneof"`
}

type ServerEnvelope_CancelTask struct {
	CancelTask *CancelTaskRequest `protobuf:"bytes,3,opt,name=cancel_task,json=cancelTask,proto3,oneof"`
}

type ServerEnvelope_Ping struct {
	Ping *ServerPing `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*ServerEnvelope_RegisterAck) isServerEnvelope_Payload() {}

func (*ServerEnvelope_RunTask) isServerEnvelope_Payload() {}

func (*ServerEnvelope_CancelTask) isServerEnvelope_Payload() {}

func (*ServerEnvelope_Ping) isServerEnvelope_Payload() {}

var File_protocol_proto_runner_proto protoreflect.FileDescriptor

const file_protocol_proto_runner_proto_rawDesc = "" +
	"\n" +
	"\x1bprotocol/proto/runner.proto\x12\x13agentflow.runner.v1\"\xd0\x04\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12;\n" +
	"\x03env\x18\x06 \x03(\v2).agentflow.runner.v1.TaskRequest.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\a \x01(\tR\n" +
	"workingDir\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\b \x01(\x03R\ttimeoutMs\x12\x16\n" +
	"\x06stream\x18\t \x01(\bR\x06stream\x12\x1d\n" +
	"\n" +
	"auth_token\x18\n" +
	" \x01(\tR\tauthToken\x12\x1d\n" +
	"\n" +
	"input_json\x18\v \x01(\fR\tinputJson\x123\n" +
	"\x06engine\x18\f \x01(\x0e2\x1b.agentflow.runner.v1.EngineR\x06engine\x12I\n" +
	"\x0esandbox_policy\x18\r \x01(\v2\".agentflow.runner.v1.SandboxPolicyR\rsandboxPolicy\x127\n" +
	"\x06docker\x18\x0e \x01(\v2\x1f.agentflow.runner.v1.DockerSpecR\x06docker\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x03\n" +
	"\rSandboxPolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1b\n" +
	"\tread_only\x18\x02 \x01(\bR\breadOnly\x12#\n" +
	"\rallow_network\x18\x03 \x01(\bR\fallowNetwork\x120\n" +
	"\x14allowed_working_dirs\x18\x04 \x03(\tR\x12allowedWorkingDirs\x12,\n" +
	"\x12allowed_read_paths\x18\x05 \x03(\tR\x10allowedReadPaths\x12.\n" +
	"\x13allowed_write_paths\x18\x06 \x03(\tR\x11allowedWritePaths\x12:\n" +
	"\x19blocked_command_fragments\x18\a \x03(\tR\x17blockedCommandFragments\x12(\n" +
	"\x10allowed_env_keys\x18\b \x03(\tR\x0eallowedEnvKeys\x12&\n" +
	"\x0fdenied_env_keys\x18\t \x03(\tR\rdeniedEnvKeys\"Z\n" +
	"\vDockerMount\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\xe1\x01\n" +
	"\n" +
	"DockerSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x19\n" +
	"\bwork_dir\x18\x02 \x01(\tR\aworkDir\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12)\n" +
	"\x10network_disabled\x18\x04 \x01(\bR\x0fnetworkDisabled\x12)\n" +
	"\x11read_only_root_fs\x18\x05 \x01(\bR\x0ereadOnlyRootFs\x128\n" +
	"\x06mounts\x18\x06 \x03(\v2 .agentflow.runner.v1.DockerMountR\x06mounts\"D\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"J\n" +
	"\x12CancelTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12HealthCheckRequest\"d\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tunix_time\x18\x03 \x01(\x03R\bunixTime\"*\n" +
	"\x0eStartedPayload\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\rStreamPayload\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\"E\n" +
	"\x0fProgressPayload\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\apercent\x18\x02 \x01(\rR\apercent\"M\n" +
	"\rResultPayload\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\voutput_json\x18\x02 \x01(\fR\n" +
	"outputJson\"F\n" +
	"\fErrorPayload\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x02 \x01(\bR\tretryable\"P\n" +
	"\x10CompletedPayload\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x04R\n" +
	"durationMs\",\n" +
	"\x10HeartbeatPayload\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xe2\x05\n" +
	"\tTaskEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x126\n" +
	"\x04type\x18\x04 \x01(\x0e2\".agentflow.runner.v1.TaskEventTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x1b\n" +
	"\trunner_id\x18\x06 \x01(\tR\brunnerId\x12?\n" +
	"\astarted\x18\x14 \x01(\v2#.agentflow.runner.v1.StartedPayloadH\x00R\astarted\x12<\n" +
	"\x06stdout\x18\x15 \x01(\v2\".agentflow.runner.v1.StreamPayloadH\x00R\x06stdout\x12<\n" +
	"\x06stderr\x18\x16 \x01(\v2\".agentflow.runner.v1.StreamPayloadH\x00R\x06stderr\x12B\n" +
	"\bprogress\x18\x17 \x01(\v2$.agentflow.runner.v1.ProgressPayloadH\x00R\bprogress\x12<\n" +
	"\x06result\x18\x18 \x01(\v2\".agentflow.runner.v1.ResultPayloadH\x00R\x06result\x129\n" +
	"\x05error\x18\x19 \x01(\v2!.agentflow.runner.v1.ErrorPayloadH\x00R\x05error\x12E\n" +
	"\tcompleted\x18\x1a \x01(\v2%.agentflow.runner.v1.CompletedPayloadH\x00R\tcompleted\x12E\n" +
	"\theartbeat\x18\x1b \x01(\v2%.agentflow.runner.v1.HeartbeatPayloadH\x00R\theartbeatB\t\n" +
	"\apayload\"\xed\x01\n" +
	"\x0fConnectRegister\x12!\n" +
	"\frunner_token\x18\x01 \x01(\tR\vrunnerToken\x12\x1b\n" +
	"\trunner_id\x18\x02 \x01(\tR\brunnerId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12\x1b\n" +
	"\thost_name\x18\a \x01(\tR\bhostName\x12\x17\n" +
	"\ahost_ip\x18\b \x01(\tR\x06hostIp\"\x9e\x01\n" +
	"\x12ConnectRegisterAck\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x122\n" +
	"\x15heartbeat_interval_ms\x18\x03 \x01(\x03R\x13heartbeatIntervalMs\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\tR\n" +
	"serverTime\"p\n" +
	"\x10ConnectHeartbeat\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12!\n" +
	"\frunner_token\x18\x02 \x01(\tR\vrunnerToken\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"-\n" +
	"\n" +
	"ServerPing\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\tR\n" +
	"serverTime\"\xe7\x01\n" +
	"\x0eRunnerEnvelope\x12B\n" +
	"\bregister\x18\x01 \x01(\v2$.agentflow.runner.v1.ConnectRegisterH\x00R\bregister\x12E\n" +
	"\theartbeat\x18\x02 \x01(\v2%.agentflow.runner.v1.ConnectHeartbeatH\x00R\theartbeat\x12?\n" +
	"\n" +
	"task_event\x18\x03 \x01(\v2\x1e.agentflow.runner.v1.TaskEventH\x00R\ttaskEventB\t\n" +
	"\apayload\"\xaa\x02\n" +
	"\x0eServerEnvelope\x12L\n" +
	"\fregister_ack\x18\x01 \x01(\v2'.agentflow.runner.v1.ConnectRegisterAckH\x00R\vregisterAck\x12=\n" +
	"\brun_task\x18\x02 \x01(\v2 .agentflow.runner.v1.TaskRequestH\x00R\arunTask\x12I\n" +
	"\vcancel_task\x18\x03 \x01(\v2&.agentflow.runner.v1.CancelTaskRequestH\x00R\n" +
	"cancelTask\x125\n" +
	"\x04ping\x18\x04 \x01(\v2\x1f.agentflow.runner.v1.ServerPingH\x00R\x04pingB\t\n" +
	"\apayload*D\n" +
	"\x06Engine\x12\x16\n" +
	"\x12ENGINE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vENGINE_HOST\x10\x01\x12\x11\n" +
	"\rENGINE_DOCKER\x10\x02*\x98\x02\n" +
	"\rTaskEventType\x12\x1f\n" +
	"\x1bTASK_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TASK_EVENT_TYPE_STARTED\x10\x01\x12\x1a\n" +
	"\x16TASK_EVENT_TYPE_STDOUT\x10\x02\x12\x1a\n" +
	"\x16TASK_EVENT_TYPE_STDERR\x10\x03\x12\x1c\n" +
	"\x18TASK_EVENT_TYPE_PROGRESS\x10\x04\x12\x1a\n" +
	"\x16TASK_EVENT_TYPE_RESULT\x10\x05\x12\x19\n" +
	"\x15TASK_EVENT_TYPE_ERROR\x10\x06\x12\x1d\n" +
	"\x19TASK_EVENT_TYPE_COMPLETED\x10\a\x12\x1d\n" +
	"\x19TASK_EVENT_TYPE_HEARTBEAT\x10\b2\xf8\x02\n" +
	"\rRunnerService\x12W\n" +
	"\aConnect\x12#.agentflow.runner.v1.RunnerEnvelope\x1a#.agentflow.runner.v1.ServerEnvelope(\x010\x01\x12M\n" +
	"\aRunTask\x12 .agentflow.runner.v1.TaskRequest\x1a\x1e.agentflow.runner.v1.TaskEvent0\x01\x12]\n" +
	"\n" +
	"CancelTask\x12&.agentflow.runner.v1.CancelTaskRequest\x1a'.agentflow.runner.v1.CancelTaskResponse\x12`\n" +
	"\vHealthCheck\x12'.agentflow.runner.v1.HealthCheckRequest\x1a(.agentflow.runner.v1.HealthCheckResponseB6Z4github.com/agent-flow/runner/protocol/proto;runnerpbb\x06proto3"

var (
	file_protocol_proto_runner_proto_rawDescOnce sync.Once
	file_protocol_proto_runner_proto_rawDescData []byte
)

func file_protocol_proto_runner_proto_rawDescGZIP() []byte {
	file_protocol_proto_runner_proto_rawDescOnce.Do(func() {
		file_protocol_proto_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_runner_proto_rawDesc), len(file_protocol_proto_runner_proto_rawDesc)))
	})
	return file_protocol_proto_runner_proto_rawDescData
}

var file_protocol_proto_runner_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protocol_proto_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_protocol_proto_runner_proto_goTypes = []any{
	(Engine)(0),                 // 0: agentflow.runner.v1.Engine
	(TaskEventType)(0),          // 1: agentflow.runner.v1.TaskEventType
	(*TaskRequest)(nil),         // 2: agentflow.runner.v1.TaskRequest
	(*SandboxPolicy)(nil),       // 3: agentflow.runner.v1.SandboxPolicy
	(*DockerMount)(nil),         // 4: agentflow.runner.v1.DockerMount
	(*DockerSpec)(nil),          // 5: agentflow.runner.v1.DockerSpec
	(*CancelTaskRequest)(nil),   // 6: agentflow.runner.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),  // 7: agentflow.runner.v1.CancelTaskResponse
	(*HealthCheckRequest)(nil),  // 8: agentflow.runner.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 9: agentflow.runner.v1.HealthCheckResponse
	(*StartedPayload)(nil),      // 10: agentflow.runner.v1.StartedPayload
	(*StreamPayload)(nil),       // 11: agentflow.runner.v1.StreamPayload
	(*ProgressPayload)(nil),     // 12: agentflow.runner.v1.ProgressPayload
	(*ResultPayload)(nil),       // 13: agentflow.runner.v1.ResultPayload
	(*ErrorPayload)(nil),        // 14: agentflow.runner.v1.ErrorPayload
	(*CompletedPayload)(nil),    // 15: agentflow.runner.v1.CompletedPayload
	(*HeartbeatPayload)(nil),    // 16: agentflow.runner.v1.HeartbeatPayload
	(*TaskEvent)(nil),           // 17: agentflow.runner.v1.TaskEvent
	(*ConnectRegister)(nil),     // 18: agentflow.runner.v1.ConnectRegister
	(*ConnectRegisterAck)(nil),  // 19: agentflow.runner.v1.ConnectRegisterAck
	(*ConnectHeartbeat)(nil),    // 20: agentflow.runner.v1.ConnectHeartbeat
	(*ServerPing)(nil),          // 21: agentflow.runner.v1.ServerPing
	(*RunnerEnvelope)(nil),      // 22: agentflow.runner.v1.RunnerEnvelope
	(*ServerEnvelope)(nil),      // 23: agentflow.runner.v1.ServerEnvelope
	nil,                         // 24: agentflow.runner.v1.TaskRequest.EnvEntry
}
var file_protocol_proto_runner_proto_depIdxs = []int32{
	24, // 0: agentflow.runner.v1.TaskRequest.env:type_name -> agentflow.runner.v1.TaskRequest.EnvEntry
	0,  // 1: agentflow.runner.v1.TaskRequest.engine:type_name -> agentflow.runner.v1.Engine
	3,  // 2: agentflow.runner.v1.TaskRequest.sandbox_policy:type_name -> agentflow.runner.v1.SandboxPolicy
	5,  // 3: agentflow.runner.v1.TaskRequest.docker:type_name -> agentflow.runner.v1.DockerSpec
	4,  // 4: agentflow.runner.v1.DockerSpec.mounts:type_name -> agentflow.runner.v1.DockerMount
	1,  // 5: agentflow.runner.v1.TaskEvent.type:type_name -> agentflow.runner.v1.TaskEventType
	10, // 6: agentflow.runner.v1.TaskEvent.started:type_name -> agentflow.runner.v1.StartedPayload
	11, // 7: agentflow.runner.v1.TaskEvent.stdout:type_name -> agentflow.runner.v1.StreamPayload
	11, // 8: agentflow.runner.v1.TaskEvent.stderr:type_name -> agentflow.runner.v1.StreamPayload
	12, // 9: agentflow.runner.v1.TaskEvent.progress:type_name -> agentflow.runner.v1.ProgressPayload
	13, // 10: agentflow.runner.v1.TaskEvent.result:type_name -> agentflow.runner.v1.ResultPayload
	14, // 11: agentflow.runner.v1.TaskEvent.error:type_name -> agentflow.runner.v1.ErrorPayload
	15, // 12: agentflow.runner.v1.TaskEvent.completed:type_name -> agentflow.runner.v1.CompletedPayload
	16, // 13: agentflow.runner.v1.TaskEvent.heartbeat:type_name -> agentflow.runner.v1.HeartbeatPayload
	18, // 14: agentflow.runner.v1.RunnerEnvelope.register:type_name -> agentflow.runner.v1.ConnectRegister
	20, // 15: agentflow.runner.v1.RunnerEnvelope.heartbeat:type_name -> agentflow.runner.v1.ConnectHeartbeat
	17, // 16: agentflow.runner.v1.RunnerEnvelope.task_event:type_name -> agentflow.runner.v1.TaskEvent
	19, // 17: agentflow.runner.v1.ServerEnvelope.register_ack:type_name -> agentflow.runner.v1.ConnectRegisterAck
	2,  // 18: agentflow.runner.v1.ServerEnvelope.run_task:type_name -> agentflow.runner.v1.TaskRequest
	6,  // 19: agentflow.runner.v1.ServerEnvelope.cancel_task:type_name -> agentflow.runner.v1.CancelTaskRequest
	21, // 20: agentflow.runner.v1.ServerEnvelope.ping:type_name -> agentflow.runner.v1.ServerPing
	22, // 21: agentflow.runner.v1.RunnerService.Connect:input_type -> agentflow.runner.v1.RunnerEnvelope
	2,  // 22: agentflow.runner.v1.RunnerService.RunTask:input_type -> agentflow.runner.v1.TaskRequest
	6,  // 23: agentflow.runner.v1.RunnerService.CancelTask:input_type -> agentflow.runner.v1.CancelTaskRequest
	8,  // 24: agentflow.runner.v1.RunnerService.HealthCheck:input_type -> agentflow.runner.v1.HealthCheckRequest
	23, // 25: agentflow.runner.v1.RunnerService.Connect:output_type -> agentflow.runner.v1.ServerEnvelope
	17, // 26: agentflow.runner.v1.RunnerService.RunTask:output_type -> agentflow.runner.v1.TaskEvent
	7,  // 27: agentflow.runner.v1.RunnerService.CancelTask:output_type -> agentflow.runner.v1.CancelTaskResponse
	9,  // 28: agentflow.runner.v1.RunnerService.HealthCheck:output_type -> agentflow.runner.v1.HealthCheckResponse
	25, // [25:29] is the sub-list for method output_type
	21, // [21:25] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_protocol_proto_runner_proto_init() }
func file_protocol_proto_runner_proto_init() {
	if File_protocol_proto_runner_proto != nil {
		return
	}
	file_protocol_proto_runner_proto_msgTypes[15].OneofWrappers = []any{
		(*TaskEvent_Started)(nil),
		(*TaskEvent_Stdout)(nil),
		(*TaskEvent_Stderr)(nil),
		(*TaskEvent_Progress)(nil),
		(*TaskEvent_Result)(nil),
		(*TaskEvent_Error)(nil),
		(*TaskEvent_Completed)(nil),
		(*TaskEvent_Heartbeat)(nil),
	}
	file_protocol_proto_runner_proto_msgTypes[20].OneofWrappers = []any{
		(*RunnerEnvelope_Register)(nil),
		(*RunnerEnvelope_Heartbeat)(nil),
		(*RunnerEnvelope_TaskEvent)(nil),
	}
	file_protocol_proto_runner_proto_msgTypes[21].OneofWrappers = []any{
		(*ServerEnvelope_RegisterAck)(nil),
		(*ServerEnvelope_RunTask)(nil),
		(*ServerEnvelope_CancelTask)(nil),
		(*ServerEnvelope_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_runner_proto_rawDesc), len(file_protocol_proto_runner_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_proto_runner_proto_goTypes,
		DependencyIndexes: file_protocol_proto_runner_proto_depIdxs,
		EnumInfos:         file_protocol_proto_runner_proto_enumTypes,
		MessageInfos:      file_protocol_proto_runner_proto_msgTypes,
	}.Build()
	File_protocol_proto_runner_proto = out.File
	file_protocol_proto_runner_proto_goTypes = nil
	file_protocol_proto_runner_proto_depIdxs = nil
}
