// AUTO-GENERATED by protocol/types/generate-runner-types.mjs
// Source: protocol/proto/runner.proto
// DO NOT EDIT MANUALLY.

export type Engine = 'host' | 'docker';

export type TaskEventType = 
  | 'started'
  | 'stdout'
  | 'stderr'
  | 'progress'
  | 'result'
  | 'error'
  | 'completed'
  | 'heartbeat';

export interface SandboxPolicy {
  enabled?: boolean;
  readOnly?: boolean;
  allowNetwork?: boolean;
  allowedWorkingDirs?: string[];
  allowedReadPaths?: string[];
  allowedWritePaths?: string[];
  blockedCommandFragments?: string[];
  allowedEnvKeys?: string[];
  deniedEnvKeys?: string[];
}

export interface DockerMount {
  source: string;
  target: string;
  readOnly?: boolean;
}

export interface DockerSpec {
  image: string;
  workDir?: string;
  user?: string;
  networkDisabled?: boolean;
  readOnlyRootFs?: boolean;
  mounts?: DockerMount[];
}

export interface TaskRequest {
  taskId: string;
  sessionId: string;
  stepId: string;
  command: string;
  args?: string[];
  env?: Record<string, string>;
  workingDir?: string;
  timeoutMs?: number;
  stream?: boolean;
  authToken?: string;
  engine?: Engine;
  sandboxPolicy?: SandboxPolicy;
  docker?: DockerSpec;
  inputJson?: unknown;
}

export interface CancelTaskRequest {
  taskId: string;
  reason?: string;
}

export interface CancelTaskResponse {
  accepted: boolean;
  message: string;
}

export interface HealthCheckResponse {
  status: string;
  version: string;
  unixTime: number;
}

export interface RunnerEventBase {
  taskId: string;
  sessionId: string;
  stepId: string;
  type: TaskEventType;
  timestamp: string;
  runnerId: string;
}

export interface StartedEvent extends RunnerEventBase {
  type: 'started';
  started: { message: string };
}

export interface StdoutEvent extends RunnerEventBase {
  type: 'stdout';
  stdout: { chunk: string };
}

export interface StderrEvent extends RunnerEventBase {
  type: 'stderr';
  stderr: { chunk: string };
}

export interface ProgressEvent extends RunnerEventBase {
  type: 'progress';
  progress: { message: string; percent: number };
}

export interface ResultEvent extends RunnerEventBase {
  type: 'result';
  result: { exitCode: number; outputJson: unknown };
}

export interface ErrorEvent extends RunnerEventBase {
  type: 'error';
  error: { message: string; retryable: boolean };
}

export interface CompletedEvent extends RunnerEventBase {
  type: 'completed';
  completed: { exitCode: number; durationMs: number };
}

export interface HeartbeatEvent extends RunnerEventBase {
  type: 'heartbeat';
  heartbeat: { message: string };
}

export type TaskEvent =
  | StartedEvent
  | StdoutEvent
  | StderrEvent
  | ProgressEvent
  | ResultEvent
  | ErrorEvent
  | CompletedEvent
  | HeartbeatEvent;
