// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, user_id, name, key_hash, key_prefix, is_active, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAPIKeyParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	KeyHash   string             `json:"key_hash"`
	KeyPrefix string             `json:"key_prefix"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.IsActive,
		arg.CreatedAt,
	)
	return err
}

const deactivateAPIKey = `-- name: DeactivateAPIKey :exec
UPDATE api_keys SET is_active = FALSE WHERE id = $1 AND user_id = $2
`

type DeactivateAPIKeyParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeactivateAPIKey(ctx context.Context, arg DeactivateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deactivateAPIKey, arg.ID, arg.UserID)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, name, key_hash, key_prefix, is_active, last_used_at, created_at FROM api_keys WHERE key_hash = $1 AND is_active = TRUE
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, name, key_hash, key_prefix, is_active, last_used_at, created_at FROM api_keys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.IsActive,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = $1 WHERE id = $2
`

type TouchAPIKeyParams struct {
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ID         string             `json:"id"`
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error {
	_, err := q.db.Exec(ctx, touchAPIKey, arg.LastUsedAt, arg.ID)
	return err
}
