// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequestLog = `-- name: GetRequestLog :one
SELECT id, user_id, conversation_id, provider_id, model, request_body, response_body, status_code, duration_ms, created_at FROM request_logs WHERE id = $1 AND user_id = $2
`

type GetRequestLogParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetRequestLog(ctx context.Context, arg GetRequestLogParams) (RequestLog, error) {
	row := q.db.QueryRow(ctx, getRequestLog, arg.ID, arg.UserID)
	var i RequestLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConversationID,
		&i.ProviderID,
		&i.Model,
		&i.RequestBody,
		&i.ResponseBody,
		&i.StatusCode,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const insertRequestLog = `-- name: InsertRequestLog :exec
INSERT INTO request_logs (id, user_id, conversation_id, provider_id, model, request_body, response_body, status_code, duration_ms, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertRequestLogParams struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	ConversationID pgtype.Text        `json:"conversation_id"`
	ProviderID     string             `json:"provider_id"`
	Model          pgtype.Text        `json:"model"`
	RequestBody    []byte             `json:"request_body"`
	ResponseBody   []byte             `json:"response_body"`
	StatusCode     pgtype.Int2        `json:"status_code"`
	DurationMs     pgtype.Int4        `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertRequestLog(ctx context.Context, arg InsertRequestLogParams) error {
	_, err := q.db.Exec(ctx, insertRequestLog,
		arg.ID,
		arg.UserID,
		arg.ConversationID,
		arg.ProviderID,
		arg.Model,
		arg.RequestBody,
		arg.ResponseBody,
		arg.StatusCode,
		arg.DurationMs,
		arg.CreatedAt,
	)
	return err
}

const insertUsageLog = `-- name: InsertUsageLog :exec
INSERT INTO usage_logs (id, user_id, api_key_id, provider_id, model, request_bytes, response_bytes, duration_ms, status_code, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertUsageLogParams struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	ApiKeyID      string             `json:"api_key_id"`
	ProviderID    string             `json:"provider_id"`
	Model         string             `json:"model"`
	RequestBytes  pgtype.Int4        `json:"request_bytes"`
	ResponseBytes pgtype.Int4        `json:"response_bytes"`
	DurationMs    pgtype.Int4        `json:"duration_ms"`
	StatusCode    pgtype.Int2        `json:"status_code"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertUsageLog(ctx context.Context, arg InsertUsageLogParams) error {
	_, err := q.db.Exec(ctx, insertUsageLog,
		arg.ID,
		arg.UserID,
		arg.ApiKeyID,
		arg.ProviderID,
		arg.Model,
		arg.RequestBytes,
		arg.ResponseBytes,
		arg.DurationMs,
		arg.StatusCode,
		arg.CreatedAt,
	)
	return err
}

const listRequestLogs = `-- name: ListRequestLogs :many
SELECT id, user_id, conversation_id, provider_id, model, status_code, duration_ms, created_at
FROM request_logs
WHERE user_id = $1
  AND ($2::text = '' OR conversation_id = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListRequestLogsParams struct {
	UserID  string `json:"user_id"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListRequestLogsRow struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	ConversationID pgtype.Text        `json:"conversation_id"`
	ProviderID     string             `json:"provider_id"`
	Model          pgtype.Text        `json:"model"`
	StatusCode     pgtype.Int2        `json:"status_code"`
	DurationMs     pgtype.Int4        `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRequestLogs(ctx context.Context, arg ListRequestLogsParams) ([]ListRequestLogsRow, error) {
	rows, err := q.db.Query(ctx, listRequestLogs,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestLogsRow{}
	for rows.Next() {
		var i ListRequestLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConversationID,
			&i.ProviderID,
			&i.Model,
			&i.StatusCode,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
