// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	IsActive   pgtype.Bool        `json:"is_active"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ProviderConfig struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	ProviderID  string             `json:"provider_id"`
	DisplayName string             `json:"display_name"`
	ApiKeyEnc   string             `json:"api_key_enc"`
	BaseUrl     pgtype.Text        `json:"base_url"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RequestLog struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	ConversationID pgtype.Text        `json:"conversation_id"`
	ProviderID     string             `json:"provider_id"`
	Model          pgtype.Text        `json:"model"`
	RequestBody    []byte             `json:"request_body"`
	ResponseBody   []byte             `json:"response_body"`
	StatusCode     pgtype.Int2        `json:"status_code"`
	DurationMs     pgtype.Int4        `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type UsageLog struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	ApiKeyID      string             `json:"api_key_id"`
	ProviderID    string             `json:"provider_id"`
	Model         string             `json:"model"`
	RequestBytes  pgtype.Int4        `json:"request_bytes"`
	ResponseBytes pgtype.Int4        `json:"response_bytes"`
	DurationMs    pgtype.Int4        `json:"duration_ms"`
	StatusCode    pgtype.Int2        `json:"status_code"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            pgtype.Text        `json:"name"`
	DefaultProvider pgtype.Text        `json:"default_provider"`
	DefaultModel    pgtype.Text        `json:"default_model"`
	RateLimitRpm    pgtype.Int4        `json:"rate_limit_rpm"`
	IsAdmin         pgtype.Bool        `json:"is_admin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
