// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderConfig = `-- name: CreateProviderConfig :exec
INSERT INTO provider_configs (id, user_id, provider_id, display_name, api_key_enc, base_url, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateProviderConfigParams struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	ProviderID  string             `json:"provider_id"`
	DisplayName string             `json:"display_name"`
	ApiKeyEnc   string             `json:"api_key_enc"`
	BaseUrl     pgtype.Text        `json:"base_url"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProviderConfig(ctx context.Context, arg CreateProviderConfigParams) error {
	_, err := q.db.Exec(ctx, createProviderConfig,
		arg.ID,
		arg.UserID,
		arg.ProviderID,
		arg.DisplayName,
		arg.ApiKeyEnc,
		arg.BaseUrl,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProviderConfig = `-- name: DeleteProviderConfig :exec
DELETE FROM provider_configs WHERE id = $1 AND user_id = $2
`

type DeleteProviderConfigParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteProviderConfig(ctx context.Context, arg DeleteProviderConfigParams) error {
	_, err := q.db.Exec(ctx, deleteProviderConfig, arg.ID, arg.UserID)
	return err
}

const getProviderConfig = `-- name: GetProviderConfig :one
SELECT id, user_id, provider_id, display_name, api_key_enc, base_url, is_active, created_at, updated_at FROM provider_configs WHERE user_id = $1 AND provider_id = $2 AND is_active = TRUE
`

type GetProviderConfigParams struct {
	UserID     string `json:"user_id"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetProviderConfig(ctx context.Context, arg GetProviderConfigParams) (ProviderConfig, error) {
	row := q.db.QueryRow(ctx, getProviderConfig, arg.UserID, arg.ProviderID)
	var i ProviderConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.DisplayName,
		&i.ApiKeyEnc,
		&i.BaseUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderConfigs = `-- name: ListProviderConfigs :many
SELECT id, user_id, provider_id, display_name, api_key_enc, base_url, is_active, created_at, updated_at FROM provider_configs WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProviderConfigs(ctx context.Context, userID string) ([]ProviderConfig, error) {
	rows, err := q.db.Query(ctx, listProviderConfigs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderConfig{}
	for rows.Next() {
		var i ProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProviderID,
			&i.DisplayName,
			&i.ApiKeyEnc,
			&i.BaseUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderConfig = `-- name: UpdateProviderConfig :exec
UPDATE provider_configs
SET display_name = $3, api_key_enc = $4, base_url = $5, updated_at = $6
WHERE id = $1 AND user_id = $2
`

type UpdateProviderConfigParams struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	DisplayName string             `json:"display_name"`
	ApiKeyEnc   string             `json:"api_key_enc"`
	BaseUrl     pgtype.Text        `json:"base_url"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProviderConfig(ctx context.Context, arg UpdateProviderConfigParams) error {
	_, err := q.db.Exec(ctx, updateProviderConfig,
		arg.ID,
		arg.UserID,
		arg.DisplayName,
		arg.ApiKeyEnc,
		arg.BaseUrl,
		arg.UpdatedAt,
	)
	return err
}
