// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, name, default_provider, default_model, rate_limit_rpm, is_admin, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserParams struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            pgtype.Text        `json:"name"`
	DefaultProvider pgtype.Text        `json:"default_provider"`
	DefaultModel    pgtype.Text        `json:"default_model"`
	RateLimitRpm    pgtype.Int4        `json:"rate_limit_rpm"`
	IsAdmin         pgtype.Bool        `json:"is_admin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.DefaultProvider,
		arg.DefaultModel,
		arg.RateLimitRpm,
		arg.IsAdmin,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, default_provider, default_model, rate_limit_rpm, is_admin, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.DefaultProvider,
		&i.DefaultModel,
		&i.RateLimitRpm,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userCount = `-- name: UserCount :one
SELECT COUNT(*) FROM users
`

func (q *Queries) UserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, userCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
